// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCAStUe71I6abEMzjJPSR6pbyAbG-qWc8w',
    appId: '1:825552205447:web:242e3483946fcee19d6a22',
    messagingSenderId: '825552205447',
    projectId: 'tipsnap-dc087',
    authDomain: 'tipsnap-dc087.firebaseapp.com',
    storageBucket: 'tipsnap-dc087.firebasestorage.app',
    measurementId: 'G-Z82466BC3B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNnoPy4GSqtcd-4AKZJPWg7iMt8cn_xrQ',
    appId: '1:825552205447:android:d4a04feacd72c1a89d6a22',
    messagingSenderId: '825552205447',
    projectId: 'tipsnap-dc087',
    storageBucket: 'tipsnap-dc087.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDO_olk76ZgIw_QZ0doNx7bl6l9exJgxk4',
    appId: '1:825552205447:ios:cf6d1055b584b9939d6a22',
    messagingSenderId: '825552205447',
    projectId: 'tipsnap-dc087',
    storageBucket: 'tipsnap-dc087.firebasestorage.app',
    iosClientId: '825552205447-jm97frt0at3o6kjgnt81odgo4qd5ng34.apps.googleusercontent.com',
    iosBundleId: 'com.example.tipsnap',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDO_olk76ZgIw_QZ0doNx7bl6l9exJgxk4',
    appId: '1:825552205447:ios:cf6d1055b584b9939d6a22',
    messagingSenderId: '825552205447',
    projectId: 'tipsnap-dc087',
    storageBucket: 'tipsnap-dc087.firebasestorage.app',
    iosClientId: '825552205447-jm97frt0at3o6kjgnt81odgo4qd5ng34.apps.googleusercontent.com',
    iosBundleId: 'com.example.tipsnap',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCAStUe71I6abEMzjJPSR6pbyAbG-qWc8w',
    appId: '1:825552205447:web:8275d8dc4db92a8e9d6a22',
    messagingSenderId: '825552205447',
    projectId: 'tipsnap-dc087',
    authDomain: 'tipsnap-dc087.firebaseapp.com',
    storageBucket: 'tipsnap-dc087.firebasestorage.app',
    measurementId: 'G-2324KNV1RQ',
  );
}
